"""Build the static Hugging Face Space in site/ from results/RESULTS.md and results/figures/.

Run after ./run_all.sh. Nothing here computes or types a number: the page is
results/RESULTS.md rendered to HTML, plus the plots it was generated with.
Upload: python -c "from huggingface_hub import HfApi; HfApi().upload_folder(
    folder_path='site', repo_id='pavanyadava07/cuda-solver-lab', repo_type='space')"
"""
import pathlib
import shutil

import markdown

ROOT = pathlib.Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
REPO = "https://github.com/pavanyadava007/cuda-solver-lab"

FIGURES = [
    ("cg_ms_per_iter.png", "CG time per iteration by grid size"),
    ("cg_bandwidth.png", "CG effective memory bandwidth"),
    ("roofline.png", "Measured FP64 roofline of the L4"),
    ("jacobi_bandwidth.png", "Jacobi sweep bandwidth"),
]

CSS = """
:root { --bg:#fafaf8; --fg:#1d1d1f; --muted:#5f6368; --line:#d9d9d4; --accent:#3b6e22; --card:#ffffff; }
@media (prefers-color-scheme: dark) {
  :root { --bg:#141414; --fg:#e8e8e6; --muted:#a0a09c; --line:#33332f; --accent:#8fc86b; --card:#1c1c1b; }
}
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
  font: 16px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1040px; margin: 0 auto; padding: 32px 16px 64px; }
h1 { font-size: 2rem; margin: 0 0 4px; }
h2 { margin-top: 2.2rem; border-bottom: 1px solid var(--line); padding-bottom: 4px; }
h3 { margin-top: 1.8rem; }
.sub { color: var(--muted); margin: 0 0 20px; }
a { color: var(--accent); }
.links a { margin-right: 16px; font-weight: 600; }
.figs { display:grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap:16px; margin-top:16px; }
figure { margin:0; background:var(--card); border:1px solid var(--line); border-radius:8px; padding:8px; }
figure img { width:100%; height:auto; display:block; background:#fff; border-radius:4px; }
figcaption { color:var(--muted); font-size:.9rem; padding-top:6px; }
.table-wrap { overflow-x:auto; }
table { border-collapse: collapse; font-size:.88rem; margin: 12px 0; min-width: 100%; }
th, td { border-bottom: 1px solid var(--line); padding: 5px 8px; text-align: right; white-space: nowrap; }
th:first-child, td:first-child { text-align: left; white-space: normal; }
th { background: var(--card); }
code { font-size: .9em; }
footer { color:var(--muted); font-size:.85rem; margin-top:40px; }
"""


def main():
    md = (ROOT / "results" / "RESULTS.md").read_text(encoding="utf-8")
    body = markdown.markdown(md, extensions=["tables"])
    body = body.replace("<table>", '<div class="table-wrap"><table>').replace("</table>", "</table></div>")

    if SITE.exists():
        shutil.rmtree(SITE)
    (SITE / "figures").mkdir(parents=True)
    figs = []
    for name, caption in FIGURES:
        src = ROOT / "results" / "figures" / name
        if src.exists():
            shutil.copy(src, SITE / "figures" / name)
            figs.append(f'<figure><img src="figures/{name}" alt="{caption}" loading="lazy">'
                        f"<figcaption>{caption}</figcaption></figure>")

    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>cuda-solver-lab</title>
<style>{CSS}</style></head>
<body><main>
<h1>cuda-solver-lab</h1>
<p class="sub">Conjugate Gradient and Jacobi solvers for the 2D Poisson equation: serial C++, OpenMP,
hand-written CUDA kernels, cuSPARSE + cuBLAS reference and Fortran OpenACC, profiled with Nsight Compute.
By Pavan Yadav Annappa.</p>
<p class="links"><a href="{REPO}">Code on GitHub</a><a href="{REPO}/blob/main/docs/DEVLOG.md">Dev log (bugs found)</a>
<a href="{REPO}/blob/main/README.md">README and method</a></p>
<h2>Plots</h2>
<div class="figs">{''.join(figs)}</div>
{body}
<footer>Static page generated by scripts/build_site.py from results/RESULTS.md. Every number comes from a
run of ./run_all.sh; reproduce it on your own GPU with the repo.</footer>
</main></body></html>
"""
    (SITE / "index.html").write_text(html, encoding="utf-8")
    (SITE / "README.md").write_text(
        "---\ntitle: cuda-solver-lab\nemoji: 📈\ncolorFrom: green\ncolorTo: gray\nsdk: static\npinned: false\n"
        "license: mit\nshort_description: CG Poisson solver study, CUDA vs OpenMP vs OpenACC on an L4\n---\n\n"
        f"Results page for {REPO}\n", encoding="utf-8")
    print("site/ written:", len(figs), "figures")


if __name__ == "__main__":
    main()
